### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by superfloh247** [Whatever510/TeslaAppDiffExtractor#1]
OSX 10.13
python3 + tk bindings installed via brew

Dialogue comes up and looks good
![Bildschirmfoto 2021-11-24 um 14 15 44](https://user-images.githubusercontent.com/26180993/143245606-dd07214e-1d34-44bd-add3-7da757b843d7.png)

pressing start leads to some console output and an error message

[INFO] Result Folder is setup
[INFO] Unzipping files...
[INFO] The files have been extracted
/Users/lindner/VSCode/TeslaAppDiffExtractor/unzipped/v3.10.8
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/lindner/VSCode/TeslaAppDiffExtractor/gui.py", line 113, in GButton_start_command
    getDiff.main(self.GLabel_old["text"], self.GLabel_new["text"], self.ios)
  File "/Users/lindner/VSCode/TeslaAppDiffExtractor/getDiff.py", line 245, in main
    locales_file_old = find("app_i18n_locales_en.json", base_dir_old).replace('\\','/')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by Whatever510** [comment]
Seems to be a naming issue. Most likely the locales_en.json has a different name in v3 app versions. I only tested it with v4. will implement a filter to prevent the program from crashing

**Comment by superfloh247** [comment]
wow, quick answer :)

looking forward to testing the next version

**Comment by Whatever510** [comment]
It was a naming issue with app versions < 4.0.0. 
The program will now skip those files, so in your case you'll only get the added and deleted assets path names. 
Will check later if i can add support for versions < 4.0.0
For the best result use a version > 4.0.0 and download it from APKmirror :)
